apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: capz-system
resources:
- https://github.com/Azure/azure-service-operator/releases/download/v2.5.0/azureserviceoperator_v2.5.0.yaml
- crds.yaml
- settings.yaml

patches:
  - patch: |- # default kustomization includes a namespace already
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: azureserviceoperator-system
  - patch: |-
      - op: test
        path: /spec/template/spec/containers/0/args/4
        value: --crd-pattern=
      - op: replace # Users can specify additional ASO CRDs. CRDs should be appended with ';'
        path: /spec/template/spec/containers/0/args/4
        value: --crd-pattern=${ADDITIONAL_ASO_CRDS:= }
    target:
      group: apps
      version: v1
      kind: Deployment
      name: azureserviceoperator-controller-manager

replacements:
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: azureserviceoperator-serving-cert
      fieldPath: metadata.namespace
    targets:
      - select:
          version: v1
        fieldPaths:
          - metadata.annotations.cert-manager\.io/inject-ca-from
        options:
          delimiter: /
          index: 0
      - select:
          group: cert-manager.io
          version: v1
          kind: Certificate
          name: azureserviceoperator-serving-cert
        fieldPaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: .
          index: 1
